spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    ### 运行时输出SQL语句
#    show-sql: true
server:
  port: 8081